### ISSUE TITLE
vk links errors [BUG] 

### ISSUE THREAD

**Issue by DormantCat** [Elytrium/LimboAuth-SocialAddon#11]
**Describe the bug**
при высоком онлайне возникают проблемы с модулем ВКонтакте.
with high online, problems arise with the VKontakte module.

**To Reproduce**
1. на сервере должно играть больше 20-30 игроков
2. пишем боту команду !привязать ник
3. бот не отвечает (иногда появляется ошибка в консоле https://pastebin.com/PVp2HAtc )
1. more than 20-30 players should play on the server
2. write a command to the bot !привязать nickname
3. the bot does not respond (sometimes an error appears in the console https://pastebin.com/PVp2HAtc )

**Expected behavior**
Бот присылает команду привязки
The bot sends a binding command

**Screenshots**
https://i.imgur.com/8ARAJwE.png

**Server Info (please complete the following information):**
- limboauth-1.0.5-jdk17 (spigotmc.org)
- LimboAuth.Social.Addon-1.0.1-jdk17 (spigotmc.org)
- limboapi-plugin-1.0.5-jdk17 (spigotmc.org)

 https://dump.velocitypowered.com/ezuhigovar.json

**Additional context**
Игроки попросту не могут привязать аккаунт к ВК, но в то же время, те кто успел привязать аккаунт - им приходят уведомления.
Так же парой плохо работает и двух этапная авторизация через вк, не каждый пользователь может подтвердить вход.

Players simply cannot link an account to the VK, but at the same time, those who managed to link an account - they receive notifications.
Also, sometimes two-stage authorization via VK does not work well, not every user can confirm the login.

**Comment by hevav** [comment]
Проверь на версии 1.0.4
