### ISSUE TITLE
[BUG] Duplicating messages after /la reload

### ISSUE THREAD

**Issue by manul694** [Elytrium/LimboAuth-SocialAddon#20]
**Describe the bug**
Message is sending (count of /la reload) + 1 times

**To Reproduce**
1. /la reload

**Expected behavior**
Message is sending once

**Screenshots**
![image](https://user-images.githubusercontent.com/48861382/212394629-2ed73866-7e91-483c-9da0-1b47f00db550.png)

**Server Info (please complete the following information):**
 - Limbo plugins latest version, velocity latest version

 - /velocity dump link [e.g. https://dump.velocitypowered.com/abcdef.json]

**Additional context**

**Comment by manul694** [comment]
After getting confirmation this problem disappears

**Comment by hevav** [comment]
1) no velocity dump
2) can't reproduce
