### ISSUE TITLE
[BUG] The plugin writes errors to the console, and the ping of the players rises

### ISSUE THREAD

**Issue by MrWeez** [Elytrium/LimboAuth-SocialAddon#25]
**Describe the bug**
Periodically, the plugin writes such errors to the console. after that, the ping increases for all players.

**To Reproduce**
No way. it just happens from time to time

**Server Info (please complete the following information):**
 - LimboAPI 1.1.0, downloaded from official github
 - LimboAuth 1.1.3, downloaded from official github
 - LimboAuth Social Addon 1.0.7, downloaded from official github

 - https://pastebin.com/NT3hfHTR

**Additional context**
https://pastebin.com/a2cfBLTD

**Comment by hevav** [comment]
Не баг плагина. Либо твой сервер атакуют, либо инет соединение нестабильно

**Comment by MrWeez** [comment]
> Не баг плагина. Либо твой сервер атакуют, либо инет соединение нестабильно

Инет стабильный, пробовал и на своих vds и на арендных.

**Comment by hevav** [comment]
> > Не баг плагина. Либо твой сервер атакуют, либо инет соединение нестабильно
> 
> Инет стабильный, пробовал и на своих vds и на арендных.

Скорее всего твой сервер атакуют. Проверь пинг до 1.1.1.1 например, когда у тебя эта проблема

**Comment by MrWeez** [comment]
> > > Не баг плагина. Либо твой сервер атакуют, либо инет соединение нестабильно
> > 
> > 
> > Инет стабильный, пробовал и на своих vds и на арендных.
> 
> Скорее всего твой сервер атакуют. Проверь пинг до 1.1.1.1 например, когда у тебя эта проблема

Прям даже не знаю... Пинг стабильный, ddos не наблюдается. Все проксировано.
![image](https://user-images.githubusercontent.com/64205495/213485566-baabeb69-3a3c-48b9-8095-d3f265f7cce1.png)

**Comment by hevav** [comment]
@MrWeez но при этом в твоих логах ошибка именно "java.net.SocketException: Network is unreachable (connect failed)"

**Comment by MrWeez** [comment]
> @MrWeez но при этом в твоих логах ошибка именно "java.net.SocketException: Network is unreachable (connect failed)"

Ладненько, пока попробую дождаться момента и проверить пинг повторно. В любом случае спасибо за оперативность и попытку помощи.
