### ISSUE TITLE
[ENHANCEMENT]  Дополнительный функционал

### ISSUE THREAD

**Issue by TheKlimoT** [Elytrium/LimboAuth-SocialAddon#6]
В момент подтверждения авторизации, после нажатия на кнопку Это я/Это не я, восстанавливать изначальную клавиатуру.

Если я подтвердил авторизацию через телеграмм, восстанавливать клавиатуру в VK, т.к. остаются 2 кнопки для подтверждения, хотя она уже пройдена.

**Comment by hevav** [comment]
Fixed
