### ISSUE TITLE
[ENHANCEMENT] 

### ISSUE THREAD

**Issue by Alienn-Know** [Elytrium/LimboAuth-SocialAddon#7]
Я не понимаю что за плагин, как он работает, как настраивать привязку к дискорду/вк/телеграмму
> нужен минимальный гайд по настройке плагина
> команды /addsocial /addtg /addvk не работают или (по крайней мере не отображают того чего ожидаешь)
>Я хотел настроить хотя бы телеграмм бота, но как то и не получилось гайда просто нет,  прописал  
telegram:
    enabled: true
    token: "ввёл сюда токен"
и всё, тупо не знаю что и как сделать дальше
надеюсь когда нибудь это будет работать)))

**Comment by moderator10000078** [comment]
пишешь боту !account link ник_майна и потом в игре вводишь комманду которую выдаст бот, привязка ВК самая неприятная, но в ДС есть закреплённое сообщение с инструкцией по настройке бота ВК

**Comment by Alienn-Know** [comment]
Спасибо большое всё заработало))) я очень рад
Я мог бы помочь написать гайд если нужно (как что установить что куда закинуть если нужно)

**Comment by Alienn-Know** [comment]
И не хватает типо в чате сообщения "Аккаунт успешно привязан" или "Ошибка, неверно введён ключ" и ещё не хватает линка по нажатию в чате допустим на телеграм

**Comment by moderator10000078** [comment]
ошибка про введённый ключ ни к чему как по мне, кликабельные ссылке вроде со временем будут

**Comment by Alienn-Know** [comment]
Спасибо
